# Generated by Django 4.2.5 on 2023-09-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia_app', '0008_remove_post_image_post_published_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
